// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnGPDnY_RoWAYpUe50NCLJHKVEykpX1HI',
    appId: '1:631628562411:web:f34601adb82726346ea3ae',
    messagingSenderId: '631628562411',
    projectId: 'chatgptbasedapp',
    authDomain: 'chatgptbasedapp.firebaseapp.com',
    storageBucket: 'chatgptbasedapp.appspot.com',
    measurementId: 'G-QVZWMM55XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF0VJN63m4ZSxQOgDJZx9O9lf5j44MEqE',
    appId: '1:631628562411:android:afcd33198e1418d96ea3ae',
    messagingSenderId: '631628562411',
    projectId: 'chatgptbasedapp',
    storageBucket: 'chatgptbasedapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLnOWqzlH9HaducAfgyqHom5Qo2JH0U4c',
    appId: '1:631628562411:ios:ae4e2a8cd17ebee06ea3ae',
    messagingSenderId: '631628562411',
    projectId: 'chatgptbasedapp',
    storageBucket: 'chatgptbasedapp.appspot.com',
    iosBundleId: 'com.example.aiDrivenEssayApplicationFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLnOWqzlH9HaducAfgyqHom5Qo2JH0U4c',
    appId: '1:631628562411:ios:a0b1f163d52799016ea3ae',
    messagingSenderId: '631628562411',
    projectId: 'chatgptbasedapp',
    storageBucket: 'chatgptbasedapp.appspot.com',
    iosBundleId: 'com.example.aiDrivenEssayApplicationFlutter.RunnerTests',
  );
}
